---
- fail: msg="Please set the 'uoc_user' variable"
  when: uoc_user is not defined

- name: Install desktop environment
  block:
    - name: Install LightDM
      apt:
        name:
          - lightdm
    - name: Configure autologin
      vars:
        lightdm_conf_dir: /etc/lightdm/lightdm.conf.d/
      block:
        - name: Create target LightDM config directory
          file:
            path: "{{ lightdm_conf_dir }}"
            state: directory
        - name: Configure LightDM to autologin
          ansible.builtin.template:
            src: lightdm-autologin.conf.j2
            dest: "{{ lightdm_conf_dir }}/autologin.conf"
    - name: Install Xfce
      apt:
        name:
          - task-xfce-desktop
        state: present
