---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "30 5 * * 0"

defaults:
  run:
    working-directory: 'mnohe.uoc-desktop'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
      - name: Run YAML lint
        uses: frenck/action-yamllint@v1
